# Generated by Django 3.0.8 on 2020-07-03 20:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for your camp', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a room name', max_length=100)),
                ('camp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bootcamp.Camp')),
            ],
        ),
        migrations.CreateModel(
            name='Workitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title', max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('camp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bootcamp.Camp')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bootcamp.Room')),
            ],
        ),
    ]
